apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: db-image
  template:
    metadata:
      labels:
        app: db-image
    spec:
      containers:
      - name: database
        image: rammohan855/blood-bank:dbimage
        ports:
        - containerPort: 3306
      imagePullSecrets:
        - name: dockerhub-secret
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi